[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Acrome"
authors = [{name = "Acrome", email = "info@acrome.net"}]
dynamic = ["version", "description"]
